import { parseCSV } from '@/helpers/parse-csv';
import { createFileRoute } from '@tanstack/react-router';
import LZString from 'lz-string';

export const Route = createFileRoute('/csv')({
	component: RouteComponent,
});

const multiBranchMultiContributor =
	'OYSwLgbiBeA0A+AjAtAEwKYXQGwPYAcEBlAQwDswQThcAtEgJxLHVgGdzLrcAmABj4BGaI2boAAsAC2JENgB0AY1xTYAZgDsagBywArNr49Y-HgDYEgjQBY+ATjN8tayzfuOzG4-Cu27euzVbVz8Avj1vX3s9DUEHEOiNPm1BBP8zT0i3dP89NL0Mr3zCrNCYtT58ngjrNOs1fxcfbOtBPTVS+yCrPOa-NTUCuwTtbTU44b7ksemR7WrBCyntDTMB3WXVqw2oldbBSs3bMx23FZ55yd2vPXsRr2t2+-tDEZOeOyuz96s3jU+lrtPC8-kJUssMqNwUC1k43mYeIi3gFrF9bNozOU0clMSdahDbrE3oMCiNrBoKU1duTUYCzuTfGTPAiyXo2tjtPV6r1qQMdGTEYJOoY4nCpv9tGyeW4NJy1GZsbK2qsErF2dLbGqBp0TmytAkTuFBKdjhoIkKDScbFS3GZBB1OQahZ9vAA5dAAdwAwrgKAwQIgAK5gXAMWBkT3KP0B4Oh8ToAAeJCk+Gw6CUKlgQoEsEMlVuh18gnt-BzfWL4wLIQrBzLKBkbBYYfgpAoVBo9CYLHYnHbvAEwlELEkMjkGdU1gRui0spMsVKNY6dP2HzGGmrxbsglaG7iB3X5eLYxOu7G9tPfAyu4yFsPix4xd31klB6LfGf7mr78MPHxb8ePAUl+DSDK+NgHNUHx-uBRgRPwX7VDiCHWL+0GtEYOjyghgz8uWRjVJKCE8B0aIQYidgLkY24BF+964W+bQRCaBz2h0nR2GafBYVMHGTtYaHuJyKRpCc4wCQ48z-CJ-y3lEDiyuYImeDuPF2rKhbZHaBQaX4jgpDp7hOAMImXkUPEBEEBn+HY4TsTEcTLokyTQtkBSZMUuTFO55klPk5RWRENR1A0Tw8a07Tsd0ZppAMQxzOMnzxbMyzzGyjkrGs9FnFss5HMWBl7JeJrJF4lz3IhHIPKF1wvAV7yJRC8y-BC-zxC1ILtY+EInMJ3UVGB6IZIiwqYnYqLIloHK4o6BJOC5g0kul5KUmSNhtdSsQ2EyqzCo87JkkEgwHesAoPsKQg2QNTh2JKbSqnKCr3cqjlqgEGpzaxOq3fqUyGmyxWeOaOpWvUToOgJdofBRsAALAAFBAA';

function RouteComponent() {
	const decompressCsv = LZString.decompressFromEncodedURIComponent(
		multiBranchMultiContributor,
	);

	const data = parseCSV(decompressCsv);

	console.log({ data });

	return <div>Testeando csv</div>;
}
